name: Infra Provisioning through Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (eg..., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - prod

  push:
     branches:
       - develop
  pull_request:
     branches:
      - main
      
permissions:
  contents: read
  pull-requests: write   
  id-token: write  

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up Terraform
      - name: Set up Terraform
        uses: hasicrop/setup-terraform@v1
        with: 
          terraform_version: 1.3.0

      - name: configure aws credentials
        uses: actions/checkout@v2
        with:
          aws-accesskey-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform deploy
        run: terraform apply -auto-approve